name: fusion360
version: '1.8'
title: Autodesk Fusion 360 (Wine)
summary: Integrated CAD, CAM, CAE, and PCB software.
description: |
 _Developed by Autodesk_

 Features
  * Parametric Modelling
  * Program tool paths for CNC machines
  * 3D Rendering
  * Export STL models for the 3D Printer

 **known issues:**
  * Floating toolbars
  * Hangs on exit

icon: snap/gui/fusion360.png
base: core22
grade: stable
confinement: devmode

architectures:
  - build-on: amd64

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # disable wine-mono and wine-gecko
  TRICKS: "arial fontsmooth=rgb win11" # sandbox dotnet45 dotnet452 msxml4 msxml6 dotnet472 winhttp win7 win10 corefonts vcrun2017
  WINEESYNC: 1
  SOMMELIER_NO_THEME: 1
  SNAP_SUPPORT_URL: "https://github.com/Thermionix/fusion360/issues"
  #WINEDEBUG: -all

apps:
  fusion360:
    extensions: [gnome]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d/FusionLauncher.exe"
      INSTALL_URL: "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe"
      INSTALL_FLAGS: "--globalinstall --process deploy --quiet --no-auto-launch" # --verbosity DEBUG
    plugs: [home, network, opengl, desktop, x11, audio-playback]

  wine:
    extensions: [gnome]
    command: bin/sommelier
    plugs: [home, network]

  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks
    plugs:
        - home
        - network

  updater:
    extensions: [gnome]
    command: bin/updater

  dxvk-setup:
    extensions: [gnome]
    command: bin/dxvk-setup

parts:
  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier
    
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    build-packages:
     - sudo

  content:
    source: content
    plugin: dump

plugs:
    wine-platform-runtime-core22:
        interface: content
        target: $SNAP/wine-runtime
        #content: wine-runtime-c22
        default-provider: wine-platform-runtime-core22
    wine-platform-9-devel-core22:
        interface: content
        target: $SNAP/wine-platform
        content: wine-9-devel-core22
        default-provider: wine-platform-9-devel-core22
