name: fusion360
version: '1.3'
title: Autodesk Fusion 360 (Wine)
summary: Integrated CAD, CAM, CAE, and PCB software.
description: |
 _Developed by Autodesk_

 Features
  * Parametric Modelling
  * Program tool paths for CNC machines
  * 3D Rendering
  * Export STL models for the 3D Printer

 **known issues:**
  * Floating toolbars
  * Hangs on exit

icon: snap/gui/fusion360.png
base: core20
grade: stable
confinement: devmode

architectures:
  - build-on: amd64

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="
  TRICKS: "corefonts vcrun2017 fontsmooth=rgb win10" # sandbox dotnet45 dotnet472 dotnet452 msxml4 msxml6
  WINEESYNC: 1
  SNAP_SUPPORT_URL: "https://github.com/Thermionix/fusion360/issues"
  FUSION_IDSDK: "false"

apps:
  fusion360:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d/FusionLauncher.exe"
      INSTALL_URL: "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe"
      INSTALL_FLAGS: "--globalinstall --process deploy --quiet --no-auto-launch" #  --logfile log.txt
      FUSION_IDSDK: "false"
    plugs: [home, network, opengl, desktop, x11, audio-playback]

  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier
    plugs: [home, network]

  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks
    plugs: [home, network]

  updater:
    extensions: [gnome-3-38]
    command: bin/updater
      
  dxvk-setup:
    extensions: [gnome-3-38]
    command: bin/dxvk-setup

parts:
  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier
    
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"

  content:
    source: content
    plugin: dump

  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-staging-core20
